/****** Object:  Database [PFAssessment]    Script Date: 10/20/2020 12:16:47 PM ******/
CREATE DATABASE [PFAssessment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PFAssessment', FILENAME = N'E:\SqlDB\PFAssessment.mdf' , SIZE = 38912KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PFAssessment_log', FILENAME = N'E:\SqlDB\PFAssessment_log.ldf' , SIZE = 892736KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PFAssessment] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PFAssessment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PFAssessment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PFAssessment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PFAssessment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PFAssessment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PFAssessment] SET ARITHABORT OFF 
GO

ALTER DATABASE [PFAssessment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PFAssessment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PFAssessment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PFAssessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PFAssessment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PFAssessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PFAssessment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PFAssessment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PFAssessment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PFAssessment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PFAssessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PFAssessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PFAssessment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PFAssessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PFAssessment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PFAssessment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PFAssessment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PFAssessment] SET RECOVERY FULL 
GO

ALTER DATABASE [PFAssessment] SET  MULTI_USER 
GO

ALTER DATABASE [PFAssessment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PFAssessment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PFAssessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PFAssessment] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PFAssessment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PFAssessment] SET  READ_WRITE 
GO


