//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAggregator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFAssessmentEntities : DbContext
    {
        public PFAssessmentEntities()
            : base("name=PFAssessmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<averages> averages { get; set; }
        public virtual DbSet<loc> loc { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<raw> raw { get; set; }
        public virtual DbSet<region> region { get; set; }
    }
}
